# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestLogin():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_login(self):
        # Test name: login
        # Step # | name | target | value
        # 1 | open | /en/ |
        self.driver.get("http://34.118.122.203/en/")
        # 2 | setWindowSize | 1552x840 |
        self.driver.set_window_size(1552, 840)
        # 3 | click | css=a > .hidden-sm-down |
        self.driver.find_element(By.CSS_SELECTOR, "a > .hidden-sm-down").click()
        # 4 | click | css=a > .hidden-sm-down |
        self.driver.find_element(By.CSS_SELECTOR, "a > .hidden-sm-down").click()
        # 5 | click | id=field-email |
        self.driver.find_element(By.ID, "field-email").click()
        # 6 | type | id=field-email | claudiu_bikis@yahoo.com
        self.driver.find_element(By.ID, "field-email").send_keys("claudiu_bikis@yahoo.com")
        # 7 | click | id=field-password |
        self.driver.find_element(By.ID, "field-password").click()
        # 8 | type | id=field-password | 1234567890
        self.driver.find_element(By.ID, "field-password").send_keys("1234567890")
        # 9 | sendKeys | id=field-password | ${KEY_ENTER}
        self.driver.find_element(By.ID, "field-password").send_keys(Keys.ENTER)
        time.sleep(3)
        assert 'container' in self.driver.page_source
