# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestChangeLanguage():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_change_language(self):
        # Test name: change_language
        # Step # | name | target | value
        # 1 | open | /en/login?back=my-account |
        self.driver.get("http://34.118.122.203/en/login?back=my-account")
        # 2 | setWindowSize | 1360x816 |
        self.driver.set_window_size(1360, 816)
        # 3 | click | id=field-email |
        self.driver.find_element(By.ID, "field-email").click()
        # 4 | type | id=field-email | claudiu_bikis@yahoo.com
        self.driver.find_element(By.ID, "field-email").send_keys("claudiu_bikis@yahoo.com")
        # 5 | click | id=field-password |
        self.driver.find_element(By.ID, "field-password").click()
        # 6 | type | id=field-password | 1234567890
        self.driver.find_element(By.ID, "field-password").send_keys("1234567890")
        # 7 | click | id=submit-login |
        self.driver.find_element(By.ID, "submit-login").click()
        # 8 | click | css=.btn-unstyle:nth-child(1) > .material-icons |
        self.driver.find_element(By.CSS_SELECTOR, ".btn-unstyle:nth-child(1) > .material-icons").click()
        # 9 | click | linkText=Română |
        self.driver.implicitly_wait(3)
        self.driver.find_element(By.XPATH, '//*[@id="_desktop_language_selector"]').click()
        self.driver.find_element(By.XPATH, '//*[@id="_desktop_language_selector"]/div/div/ul/li[2]/a').click()
        time.sleep(2)
        # 10 | click | css=.logout |
        self.driver.find_element(By.CSS_SELECTOR, ".logout").click()
        assert 'Română' in self.driver.page_source


