# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestMyorder():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_myorder(self):
        # Test name: my_order
        # Step # | name | target | value
        # 1 | open | /en/login?back=my-account |
        self.driver.get("http://34.118.122.203/en/login?back=my-account")
        # 2 | setWindowSize | 1360x816 |
        self.driver.set_window_size(1360, 816)
        # 3 | click | id=field-email |
        self.driver.find_element(By.ID, "field-email").click()
        # 4 | type | id=field-email | claudiu_bikis@yahoo.com
        self.driver.find_element(By.ID, "field-email").send_keys("claudiu_bikis@yahoo.com")
        # 5 | click | id=field-password |
        self.driver.find_element(By.ID, "field-password").click()
        # 6 | type | id=field-password | 1234567890
        self.driver.find_element(By.ID, "field-password").send_keys("1234567890")
        # 7 | click | id=submit-login |
        self.driver.find_element(By.ID, "submit-login").click()
        time.sleep(2)
        # 8 | click | css=#category-15 > .dropdown-item |
        self.driver.find_element(By.CSS_SELECTOR, "#category-15 > .dropdown-item").click()
        # 9 | click | css=.js-product:nth-child(6) img |
        self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(6) img").click()
        # 10 | click | css=.add-to-cart |
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
        time.sleep(2)
        assert 'modal-content' in self.driver.page_source
        self.driver.find_element(By.XPATH, '//*[@id="blockcart-modal"]/div/div/div[2]/div/div[2]/div/div/a').click()
        self.driver.find_element(By.XPATH, '//*[@id="main"]/div/div[2]/div[1]/div[2]/div/a').click()
        time.sleep(2)
        # 13 | click | name=confirm-addresses |
        self.driver.find_element(By.NAME, "confirm-addresses").click()
        assert 'address' in self.driver.page_source
        # 14 | click | name=confirmDeliveryOption |
        self.driver.find_element(By.NAME, "confirmDeliveryOption").click()
        # 15 | click | id=conditions_to_approve[terms-and-conditions] |
        self.driver.find_element(By.ID, "conditions_to_approve[terms-and-conditions]").click()
        # 16 | click | css=.ps-shown-by-js > .btn |
        self.driver.find_element(By.CSS_SELECTOR, ".ps-shown-by-js > .btn").click()
        time.sleep(3)
        assert 'Your order is confirmed' in self.driver.page_source
        # 17 | click | css=.logout |
        self.driver.find_element(By.CSS_SELECTOR, ".logout").click()
        time.sleep(2)
