# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestForgotPasswordReademEmail():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_forgot_password_readem_email(self):
    # Test name: forgot_password_bag
    # Step # | name | target | value
    # 1 | open | /en/login?back=my-account | 
    self.driver.get("http://34.118.122.203/en/login?back=my-account")
    # 2 | setWindowSize | 1360x816 | 
    self.driver.set_window_size(1360, 816)
    # 3 | click | linkText=Forgot your password? | 
    self.driver.find_element(By.LINK_TEXT, "Forgot your password?").click()
    # 4 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 5 | type | id=email | sdasdsd@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("readem@gmail.com")
    # 6 | click | id=send-reset-link | 
    self.driver.find_element(By.ID, "send-reset-link").click()
    time.sleep(3)
    assert 'If this email address has been registered in our shop, you will receive a link to reset your password at readem@gmail.com.' in self.driver.page_source
  
